"""add_column_status_to_reviews_table-set_nullable_true

Revision ID: b7ff6413f222
Revises: 5c7102f6ea4d
Create Date: 2026-03-03 00:58:06.169941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ff6413f222'
down_revision: Union[str, None] = '5c7102f6ea4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('status', sa.String(length=20), nullable=False))
    op.alter_column('reviews', 'suitability_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'confidence',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('reviews', 'ai_decision',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reviews', 'effective_decision',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('reviews', 'ai_reasoning',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reviews', 'ai_justification_note',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('reviews', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'model_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('reviews', 'ai_justification_note',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reviews', 'ai_reasoning',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('reviews', 'effective_decision',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('reviews', 'ai_decision',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('reviews', 'confidence',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('reviews', 'suitability_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('reviews', 'status')
    # ### end Alembic commands ###
