"""upgrade_tables_accounts-reviews

Revision ID: 0eb0e2d65795
Revises: b2c38be40b3d
Create Date: 2026-03-02 05:57:20.017849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eb0e2d65795'
down_revision: Union[str, None] = 'b2c38be40b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('ai_decision', sa.String(length=20), nullable=False))
    op.add_column('reviews', sa.Column('effective_decision', sa.String(length=20), nullable=False))
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_column('reviews', 'decision')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('decision', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'effective_decision')
    op.drop_column('reviews', 'ai_decision')
    # ### end Alembic commands ###
