"""create reviews table

Revision ID: b2c38be40b3d
Revises: 9eeea7f614d2
Create Date: 2026-03-02 04:29:45.968032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2c38be40b3d'
down_revision: Union[str, None] = '9eeea7f614d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('suitability_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=False),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('ai_reasoning', sa.Text(), nullable=False),
    sa.Column('ai_justification_note', sa.Text(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    # ### end Alembic commands ###
